apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationviewview
  labels:
    app: reservationview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationview
  template:
    metadata:
      labels:
        app: reservationview
    spec:
      containers:
        - name: reservationview
          image: 050229413886.dkr.ecr.ap-southeast-2.amazonaws.com/reservationview:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5