server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/** 
        - id: room
          uri: http://localhost:8082
          predicates:
            - Path=/roomInfos/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**            
        - id: reservationview
          uri: http://localhost:8084
          predicates:
            - Path=/reservationviews/**     
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/roomInfos/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: reservationview
          uri: http://reservationview:8080
          predicates:
            - Path=/reservationviews/**     
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080